baseURL: "https://nhagiaodich.com"
languageCode: en-us
title: Nhà Giao Dịch
theme: PaperMod
# pagination.pagerSize: 24
paginate: 24

params:
  env: production
  homeInfoParams:
    Title: "Xin chào"
    Content: "Chào mừng đến với Blog Nhà Giao Dịch. Đây là website cung cấp các thông tin bổ ích về giao dịch. Hy vọng các bạn sẽ tìm được công thức giao dịch chiến thắng của mình ở đây. Chúc các bạn trở thành Trader có lợi nhuận ổn định."

  # disqusShortname: nhagiaodich1
  # comments: true
  # meta:
  #   favicon: false
  #   svg: false
  #   faviconVersion: "1"

  socialIcons:
    - name: other
      url: "https://one.exnesstrack.net/a/s0cxkwr4tg?platform=mobile&pid=mobile_share"
    - name: twitter
      url: "https://twitter.com/nhagiaodichcom"
    - name: tiktok
      url: "https://tiktok.com/@nhagiaodichcom"
    - name: facebook
      url: "https://www.facebook.com/nhagiaodichcom"
    - name: youtube
      url: "https://www.youtube.com/@nhagiaodich_com"
    - name: email
      url: "mailto:nhagiaodichfx@gmail.com"

sitemap:
  changeFreq: ""
  disable: false
  filename: sitemap.xml
  priority: -1

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: categories
      name: Phân loại
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Lưu trữ
      url: /archives/
      weight: 30
    - identifier: search
      name: Tìm kiếm
      url: /search/
      weight: 40    
    - identifier: about
      name: Buy me a coffee
      url: /buymeacoffee/
      weight: 50
    